### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by mianzg** [ds4owd-001/project-jonathanoti#3]
@jonathanoti 
Congrats again on accomplishing your capstone project! We are happy that you went through the course with us and applied the skills in the project.

I am reviewing your project on "Access to WASH Services in Schools in Sub-Saharan Africa". Note that my review does not have any assessment on the writing content of the report, but I did enjoy reading it and learnt new stuff.

Please find the detailed feedback in the next section.

**Comment by mianzg** [comment]
@jonathanoti Hello, this is really an awesome project with report and I have truly enjoyed everything. You completed all required items in the rubrics and you have an elegant code style. All aspects in technical, data, and intellectual are so nicely done. The code style is very elegant too.

I can only offer very minor suggestions. 
1. You used multiple times %in% for a vector containing only one item. Did you experiment with different things? I think using == is sufficient here.
2. For figure 4-6, consider to fix y-axis top lim to be 100. If we put these figures together, the current y scale is different.

**Comment by jonathanoti** [comment]
@mianzg Thank you for the feedback and comments.

I am glad that you enjoyed reading my report.

Yes, I was experimenting with different things. 
However, I have updated the report with all your suggestions implemented. 

Thank you and the team for the amazing opportunity.
